name: 'NUnit Github Comment'
description: 'Generates a GitHub comment report from NUnit XML test results'
inputs:
  inputXmlPath:
    description: 'XML input file path'
    required: true
  outputFilePath:
    description: 'GitHub comment output file path'
    default: ''
    required: false
runs:
  using: "composite"
  steps:
    - run: sudo python ${{ github.action_path }}/main.py ${{ inputs.inputXmlPath }} ${{ inputs.outputFilePath }}
      shell: bash
branding:
  icon: 'message-circle'
  color: 'blue'
